### PR TITLE
Adds reason support for kicks and bans to the server.

### PR DESCRIPTION
**Pull request by Iamgoofball**
attorney_online_remake_2018-10-17_16-18-36
attorney_online_remake_2018-10-17_16-20-08

If a client is on 2.6.0:
They'll get the above popup with a reason.

If a client is below that:
They'll get a popup saying they were kicked/banned and that's that.

### CODE REVIEW

**Comment by oldmud0** [comment]
What happens if one OK button is clicked before the other?

**Comment by Iamgoofball** [comment]
You have to click them in order of disconnect then the actual reason prompt. It doesn't let you cheat.

**Comment by oldmud0** [comment]
So both dialogs are modal with a specific order of modality? I'd rather just have one dialog, thank you very much.

**Comment by Iamgoofball** [comment]
I agree and I tried that, the issue was that the client registers that it's disconnected before it processes the sent kk/kb messages. I need to dig into some of the networking stuff.

**Pull request merged**
